### Importing Numpy

In [1]:
#Importing numpy
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

### Importing data to check the incomplete data

In [3]:
#Importing raw data
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header = 1, autostrip = True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
temp_fill = np.nanmax(raw_data_np) + 1
temp_fill

68616520.0

In [5]:
#finding the temporary mean to separate the columns for strings and numbers
temp_mean = np.nanmean(raw_data_np, axis = 0)
temp_mean

C:\Users\peppy_lunatic\AppData\Local\Temp\ipykernel_5996\4085619630.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data_np, axis = 0)


array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [6]:
#savings the initial stats to check it while cleaning
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                            np.nanmean(raw_data_np, axis = 0),
                            np.nanmax(raw_data_np, axis = 0)])
temporary_stats

C:\Users\peppy_lunatic\AppData\Local\Temp\ipykernel_5996\2033792930.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
C:\Users\peppy_lunatic\AppData\Local\Temp\ipykernel_5996\2033792930.py:3: RuntimeWarning: Mean of empty slice
  np.nanmean(raw_data_np, axis = 0),
C:\Users\peppy_lunatic\AppData\Local\Temp\ipykernel_5996\2033792930.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [7]:
#identifying the column index where whe value is string/nan using the temporary mean
columns_string = np.argwhere(np.isnan(temp_mean)).squeeze()
columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [8]:
#identifying the column index where whe value is numeric using the temporary mean
columns_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Importing data by separating the strings and numbers

In [9]:
data_string = np.genfromtxt("loan-data.csv",
                            delimiter = ';',
                            skip_header = 1,
                            usecols = columns_string,
                            autostrip = True,
                            dtype = str)
data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [10]:
data_numeric = np.genfromtxt("loan-data.csv",
                            delimiter = ';',
                            skip_header = 1,
                            usecols = columns_numeric,
                            autostrip = True,
                            filling_values = temp_fill)
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Saving the headers

In [11]:
#loading the dataset again for headers only
headers_full = np.genfromtxt("loan-data.csv",
                            delimiter = ';',
                            skip_footer = np.shape(raw_data_np)[0],
                            autostrip = True,
                            dtype = str)
headers_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [12]:
#seaprating the headers for strings and numbers
headers_string, headers_numeric = headers_full[columns_string], headers_full[columns_numeric]

In [13]:
headers_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [14]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Creating checkpoints

In [15]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [16]:
checkpoint_test = checkpoint('checkpoint-test', headers_string, data_string)
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Manipulating issue date

In [17]:
#changing the header name
headers_string[0] = 'issue_date'
headers_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
np.unique(data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [19]:
#removing the year and extracting months only
data_string[:,0] = np.char.strip(data_string[:,0], '-15')

In [20]:
np.unique(data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [21]:
months = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [22]:
#creating a for loop to change the month name to month code whereas empty cell will be talen as 0
for i in range(13):
    data_string[:,0] = np.where(data_string[:,0] == months[i],
                                i,
                                data_string[:,0])
    

In [23]:
np.unique(data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Manipulating loan status

In [24]:
np.unique(data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [25]:
#defining the status of the loan term
status_bad = ['', 'Charged Off', 'Default', 'Late']

In [26]:
#assigning value of 0 to bad loan term including empty data and 1 to ood term
data_string[:,1] = np.where(np.isin(data_string[:,1], status_bad), 0, 1)

In [27]:
np.unique(data_string[:,1])

array(['0', '1'], dtype='<U69')

### Manipulating loan term

In [28]:
#changing the header name to make it more specific
headers_string[2] = 'loan_term'

In [29]:
np.unique(data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [30]:
#stripping months from the loan_term to get a numeric value
data_string[:,2] = np.char.strip(data_string[:,2], ' months')
data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [31]:
data_string[:,2] = np.where(data_string[:,2] == '',
                            '60',
                            data_string[:,2])
data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [32]:
np.unique(data_string[:,2])

array(['36', '60'], dtype='<U69')

### Identifying grade and sub grade

In [33]:
np.unique(data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [34]:
np.unique(data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

### Filling sub grade

In [35]:
for i in np.unique(data_string[:,3])[1:]:
    data_string[:,4] = np.where((data_string[:,4] == '') & (data_string[:,3] == i),
                                           i + '5',
                                           data_string[:,4])

In [36]:
np.unique(data_string[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [37]:
data_string[:,4] = np.where(data_string[:,4] == '',
                            'H1',
                            data_string[:,4])

In [38]:
np.unique(data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

### Removing grade

In [39]:
data_string = np.delete(data_string, 3, axis = 1)

In [40]:
data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [41]:
headers_string = np.delete(headers_string, 3)

In [42]:
headers_string

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Converting sub grade

In [43]:
np.unique(data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [44]:
keys = list(np.unique(data_string[:,3]))
values = list(range(1, np.unique(data_string[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys,values))

In [45]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [46]:
for i in np.unique(data_string[:,3]):
    data_string[:,3] = np.where(data_string[:,3] == i,
                                dict_sub_grade[i],
                                data_string[:,3])

In [47]:
np.unique(data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification status

In [48]:
headers_string

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [49]:
np.unique(data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [50]:
data_string[:,4] = np.where((data_string[:,4] == '') | (data_string[:,4] == 'Not Verified'), 0, 1)

In [51]:
np.unique(data_string[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [52]:
data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [53]:
np.char.strip(data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [54]:
loan_id = np.char.strip(data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_id.astype(dtype = int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [55]:
data_numeric[:,0].astype(dtype = int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [56]:
np.array_equal(loan_id.astype(dtype = int), data_numeric[:,0].astype(dtype = int))

True

In [57]:
data_string = np.delete(data_string, 5, axis = 1)
headers_string = np.delete(headers_string, 5)

In [58]:
data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [59]:
headers_string

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### State address

In [60]:
headers_string[5] = "state_address"
headers_string

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [61]:
states_name, states_count = np.unique(data_string[:,5], return_counts = True)
states_name_sorted = np.argsort(-states_count)
states_name[states_name_sorted], states_count[states_name_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [62]:
data_string[:,5] = np.where(data_string[:,5] == '',
                            0,
                            data_string[:,5])

In [63]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [64]:
data_string[:,5] = np.where(np.isin(data_string[:,5],states_west), 1, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_south), 2, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_midwest), 3, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5],states_east), 4, data_string[:,5])

In [65]:
np.unique(data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting strings to integers

In [66]:
data_string

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [67]:
data_string = data_string.astype(dtype = int)

In [68]:
data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint string

In [69]:
checkpoint_string = checkpoint('Checkpoint-string', headers_string, data_string)

In [70]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [71]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [72]:
np.array_equal(data_string, checkpoint_string['data'])

True

### substituting filler values

In [73]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [74]:
data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [75]:
temp_fill

68616520.0

In [76]:
np.isin(data_numeric[:,0], temp_fill).sum()

0

### Funded amount

In [77]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [78]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [79]:
#substituting the temporary fill with the minimum amount
data_numeric[:,2] = np.where(data_numeric[:,2] == temp_fill,
                             temporary_stats[0, columns_numeric[2]],
                             data_numeric[:,2])

In [80]:
data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Loan amount, Interest Rate, Installment and Total Payment

In [81]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [82]:
#substituting the temporary fill with the maximum value
for i in [1, 3, 4, 5]:
    data_numeric[:,i] = np.where(data_numeric[:,i] == temp_fill,
                             temporary_stats[2, columns_numeric[i]],
                             data_numeric[:,i])

In [83]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [84]:
temporary_stats[2, columns_numeric[4]]

1372.97

### Exchange rate Euro to Usd

In [85]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ",", autostrip = True, usecols = 3, skip_header=1)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [86]:
data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [87]:
exchange_rate = data_string[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [88]:
exchange_rate.shape

(10000,)

In [89]:
data_string.shape

(10000, 6)

In [90]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [91]:
data_numeric = np.hstack((data_numeric, exchange_rate))

In [92]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [93]:
headers_numeric = np.concatenate((headers_numeric, np.array(["exchange_rate"])))

In [94]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

### From USD to Euro

In [95]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [96]:
data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [97]:
columns_usd = np.array([1, 2, 4 ,5])

In [98]:
for i in columns_usd:
    data_numeric = np.hstack((data_numeric, np.reshape(data_numeric[:,i] / data_numeric[:,6], (10000,1))))

In [99]:
data_numeric.shape

(10000, 11)

In [100]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Adding header names

In [101]:
additional_headers = np.array([column_name + '_EUR' for column_name in headers_numeric[columns_usd]])

In [102]:
additional_headers

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [103]:
headers_numeric = np.concatenate((headers_numeric, additional_headers))

In [104]:
headers_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [105]:
headers_numeric[columns_usd] = np.array([column_name + '_USD' for column_name in headers_numeric[columns_usd]])

In [106]:
headers_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [107]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [108]:
headers_numeric = headers_numeric[columns_index_order]

In [109]:
headers_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [110]:
data_numeric = data_numeric[:,columns_index_order]

In [111]:
data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

### Interest rate

In [112]:
headers_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [113]:
data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [114]:
data_numeric[:,5] = data_numeric[:,5]/100

In [115]:
data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint numeric

In [116]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", headers_numeric, data_numeric)

In [117]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [118]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [119]:
np.array_equal(checkpoint_numeric['data'], data_numeric)

True

### Combining the datasets

In [120]:
checkpoint_string['data'].shape

(10000, 6)

In [121]:
checkpoint_numeric['data'].shape

(10000, 11)

In [122]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_string['data']))

In [123]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [124]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [125]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [126]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_string['header']))

In [127]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'loan_term', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

### Sorting data

In [128]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [130]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [132]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

### Saving the output

In [133]:
loan_data = np.vstack((header_full, loan_data))

In [135]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [136]:
np.savetxt("Preprocessed-Data.csv",
           loan_data,
           delimiter = ",",
           fmt = "%s")